# ##################################
# ###### mlflow Parameters ####### #
# ##################################

mlflow_uri: https://ai4medicine-mlflow.com
mlflow_user: fbqryN3pJxqqJyBK
mlflow_pass: rB4xLdfc6hmCs5Nz
# ToDo: redeploy artifact storage to be served over https for security against man in the middle attacks
#mlflow_artifact_uri: https://www.ai4medicine-mlflow.com/minio
mlflow_artifact_uri: http://ai4medicine-mlflow.com:9000
mlflow_artifact_user: 8KSKLgrwCvMHGxfh
mlflow_artifact_pass: KUMYJAzuKPbeZ55L
mlflow_experiment: debug

# #################################
# ###### Model Parameters ####### #
# #################################

model: model_name
parameter 1: 2
parameter 2: 0.001

# ##################################
# #### Data Loader Parameters #### #
# ##################################

dataset to use:  # oura, stanford
  - dataset 1
  - dataset 2

preprocessing parameter 1: 5
preprocessing parameter 2: 0.5

number of features: 1
feature choice:
  - feature 1
  - feature 2

# #################################
# #### Evaluation Parameters #### #
# #################################

predict on: train  # val or test

metrics:
  - accuracy
  - precision
  - recall

# #################################
# ### Visualization Parameters ## #
# #################################

save plots as artifacts: True
plot type:
  - ComparePredGT